[tool.briefcase]
project_name = "Beeware Custom Lib Example"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/beewarecustomlibexample"
license = "BSD license"
author = 'Johnson Shek'
author_email = "zasoliton@gmail.com"

[tool.briefcase.app.beewarecustomlibexample]
formal_name = "Beeware Custom Lib Example"
description = "Beeware using custom library example"
icon = "src/beewarecustomlibexample/resources/beewarecustomlibexample"
sources = ['src/beewarecustomlibexample']
requires = []


[tool.briefcase.app.beewarecustomlibexample.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.beewarecustomlibexample.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.beewarecustomlibexample.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.beewarecustomlibexample.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.beewarecustomlibexample.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
